#!/bin/sh
alias j='z'
alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

alias ll="ls -al"

# git related commands
alias gl='git log'
alias gc='git commit -am'
alias gp='git pull origin'
alias gf='git fetch origin'

# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Remarkable
alias remarkable_ssh='ssh root@10.11.99.1'
alias restream='restream -p'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

alias mach_java_mode="export SDKMAN_DIR="$HOME/.sdkman" && [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh""

alias m="git checkout master"
alias s="git checkout stable"

# Custom alias for git related commands 
alias g="git"
alias gb="g branch"
alias gba="g branch -a"
alias gbr="g branch -r"
alias ga="g add ." # update to add all instead of interactive
alias gs="g status -s"
alias gl="g l"
alias gls="g log --color --abbrev-commit --stat"
alias glg="g log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --branches"
alias gd="g diff"
alias gdc="g diff --cached"
alias gds="g diff --stat"
alias gcc="g commit -m"
alias gcvc="g commit -v"
alias gca="g commit --amend"
alias gcav="g commit --amend --verbose"
alias gce="g commit --amend --no-edit"
alias gcev="g commit --amend --no-edit --verbose"
alias gsh="g show"
alias gshe="g show ':(exclude)package-lock.json'"
alias gco="g checkout"
alias gcob="g checkout -b"
alias gri="g rebase --interactive"
alias grc="g rebase --continue"
alias gra="g rebase --abort"
alias gundos="g reset --soft HEAD~1"
alias gundoh="g reset --hard HEAD~1"
alias gundom="g reset --mixed HEAD~1"
alias gunstage="g reset HEAD --"
alias gst="g st"
alias gsts="g sts"
alias gstsp="g stsp"
alias gstl="g stl"
alias gsta="g sta"
alias gstd="g std"
alias gstp="g stp"
alias gstsh="g stsh"
alias gch="g cherry-pick"
alias gchc="g cherry-pick --continue"
alias gcha="g cherry-pick --abort"
alias gpl="g pl"
alias gps="g ps"
alias gpsf="g psf"
alias gcor="g cor"
alias greb="g reb"
alias gfbc="g fbc"
alias gbm="g bm"
alias gdm="g dm"
alias gfb="g fb"
alias gft="g ft"
alias gfc="g fc"
alias gfm="g fm"
alias gpr="g pr"

# Create a journal entry
# This creates a note with file name of date.md
alias note='nvim $(date -v-1d "+%d-%m-%Y").md'

# Alias specifically for tmux new session 
alias new='tmux new'

# Alias for java related commands 
alias mvnci='mvn clean install -DskipTests'
alias jstart='java -jar target/app.jar'

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
